---
- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Ensure ~/.config/personal directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/personal"
    state: directory
    mode: '0755'

- name: Ensure secrets.env file exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/personal/secrets.env"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Create Go workspace directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go"
    state: directory
    mode: '0755'

- name: Create Go bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go/bin"
    state: directory
    mode: '0755'

- name: Create src directory for GitHub projects
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go/src/github.com"
    state: directory
    mode: '0755'

- name: Create src directory for my GitHub projects
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go/src/github.com/pietdaniel"
    state: directory
    mode: '0755'

- name: Create hacks folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/hacks"
    state: directory
    mode: '0755'

- name: Create /usr/local/bin directory
  become: yes
  ansible.builtin.file:
    path: "/usr/local/bin"
    state: directory
    mode: '0755'

- name: Create /usr/local/opt directory
  become: yes
  ansible.builtin.file:
    path: "/usr/local/opt"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"

- name: Create new-day-counter folder for new-day script
  become: yes
  ansible.builtin.file:
    path: "/usr/local/opt/new-day-counter"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
