---
# RedHat/Amazon Linux shell package installation

- name: Install shell packages via DNF
  become: yes
  ansible.builtin.dnf:
    name:
      - zsh
      - tmux
    state: present

- name: Install starship
  ansible.builtin.shell: |
    curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship

- name: Install atuin
  ansible.builtin.shell: |
    curl -sSL https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.atuin/bin/atuin"
