repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.0
    hooks:
      - id: trufflehog
        args:
          - --regex
          - --entropy
          - --since-commit=HEAD
