packer_dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
packer_repo: "https://github.com/wbthomason/packer.nvim"

dotfiles:
  - src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
  - src: config.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/config.lua"
